### ISSUE TITLE
Typo in function name: GetRevistionBranch()

### ISSUE THREAD

**Issue by Cidan** [bndr/gojenkins#33]
Function name in `Build` is called `GetRevistionBranch()` instead of `GetRevisionBranch()`, and it also is broken with:

```
panic: runtime error: index out of range

goroutine 34 [running]:
panic(0x86e160, 0xc82000a0b0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/bndr/gojenkins.(*Build).GetRevistionBranch(0xc82060b200, 0x0, 0x0)
        /git/ops/src/github.com/bndr/gojenkins/build.go:403 +0x188
```

**Comment by Cidan** [comment]
I see that you fixed the name; here's a fix for the panic:

Change line 403 to:

`if len(a.LastBuiltRevision.Branch) > 0 && a.LastBuiltRevision.Branch[0].SHA1 != "" {`
