### ISSUE TITLE
jenkins.GetBuild cause process down

### ISSUE THREAD

**Issue by yehuis4** [bndr/gojenkins#5]
When I call jenkins.GetBuild frequently in my web project, the process would down with following error trace：

 panic: Get http://XXXXXXXXXXX/job/test-JTGVV/api/json: EOF

goroutine 189 [running]:
runtime.panic(0x8a3c80, 0xc2101b4780)
	/usr/local/go/src/pkg/runtime/panic.c:266 +0xb6
github.com/bndr/gojenkins.(*Requester).Do(0xc2100c76e0, 0x975660, 0x3, 0xc2101bbcf0, 0xf, ...)
	/home/yehui/go/src/github.com/bndr/gojenkins/request.go:161 +0xb57
github.com/bndr/gojenkins.(*Requester).GetJSON(0xc2100c76e0, 0xc2101bbcf0, 0xf, 0x7c58e0, 0xc210331800, ...)
	/home/yehui/go/src/github.com/bndr/gojenkins/request.go:61 +0x15a
github.com/bndr/gojenkins.(*Job).Poll(0xc2101bf020, 0x5)
	/home/yehui/go/src/github.com/bndr/gojenkins/job.go:323 +0x57
github.com/bndr/gojenkins.(*Job).GetParameters(0xc2101bf020, 0xc21033c800, 0x41432b, 0xaa4510)
	/home/yehui/go/src/github.com/bndr/gojenkins/job.go:242 +0x35
github.com/bndr/gojenkins.(*Job).InvokeSimple(0xc2101bf020, 0x0, 0x5)
	/home/yehui/go/src/github.com/bndr/gojenkins/job.go:273 +0x54
github.com/bndr/gojenkins.(*Jenkins).BuildJob(0xc210070330, 0xc2101a9140, 0xa, 0x0, 0x0, ...)
	/home/yehui/go/src/github.com/bndr/gojenkins/jenkins.go:173 +0x123
rnd-github.huawei.com/paas/application-manager/util/pipelineJenkins.ExecuteJob(0xc2101a9140, 0xa, 0x24, 0x0, 0x0)

**Comment by bndr** [comment]
Thanks, I'll look into it

**Comment by bndr** [comment]
Can you provide a bit of code that causes this bug?

**Comment by yehuis4** [comment]
func GetJobBuildResult(jobName string, buildNum int64) (result string, log string) {
	build := jenkins.GetBuild(jobName, buildNum)
	for build == nil {
		time.Sleep(2 * time.Second)
		build = jenkins.GetBuild(jobName, buildNum)
	}

	result = build.GetResult()
	log = build.GetConsoleOutput()
	return
}
