### ISSUE TITLE
go test panic on master

### ISSUE THREAD

**Issue by bronzdoc** [bndr/gojenkins#61]
Hi, I'm trying to contribute with this enhancement https://github.com/bndr/gojenkins/issues/34 but `go test` is throwing a panic. I haven't changed or added any code,  i just `go get` the project and ran the test suite. Any help is appreciated, thanks.

```
$ go test

--- FAIL: TestCreateJobs (0.00s)
        Error Trace:    jenkins_test.go:29
        Error:          Expected nil, but got: &errors.errorString{s:"401"}
        Error Trace:    jenkins_test.go:30
        Error:          Expected value not to be nil.
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x481521]

goroutine 18 [running]:
panic(0x68b220, 0xc42000c230)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc42013c0c0)
        /usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x68b220, 0xc42000c230)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/bndr/gojenkins.TestCreateJobs(0xc42013c0c0)
        /home/bronzdoc/gocode/src/github.com/bndr/gojenkins/jenkins_test.go:31 +0x1f1
testing.tRunner(0xc42013c0c0, 0x7058e8)
        /usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL    github.com/bndr/gojenkins       0.011s
```

go env:
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/bronzdoc/gocode"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build008091184=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

```
Linux version 4.9.0-0.bpo.1-amd64 (debian-kernel@lists.debian.org) (gcc version 4.9.2 (Debian 4.9.2-10) ) #1 SMP Debian 4.9.2-2~bpo8+1 (2017-01-26)

```

**Comment by bndr** [comment]
You need a running Jenkins instance to test the code, take a look at the travis build code: https://github.com/bndr/gojenkins/blob/master/.travis.yml

**Comment by bronzdoc** [comment]
I do have a jenkins instance running and listening on `8080`
